spring.application.name=HandyReact
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# MyBatis
mybatis.mapper-locations=classpath:mapper/**/*.xml

mybatis.type-aliases-package=org.handy.handyreact.dto

# MyBatis _ ?? ? ?? ??? ???? ??? ?? (?: user_name -> userName)
mybatis.configuration.map-underscore-to-camel-case=true

# MyBatis ?? SQL ?? ?? (??? ??? ??? ????? ?? ??)
logging.level.org.handy.handyreact.mapper=debug